import sys

def indel_diff(vsnp_txt, iinfo_txt, indel_txt):
	'''
	#######################################
	INPUT:
	vsnp_txt: a text filepath generated by filtering with the -v bcftools command
	iinfo_txt: a text filepath generated by filtering with the -i bcftools command
	---------------------------------------
	OUTPUT:
	indel_txt: a text filepath that contains all examples in either input that is not present
		   in the other file, in the following format:
	CHROM | VERSION (-v or -i) | POS
	#######################################
	'''
	# opens input files, gives write permissions to output
	with open(vsnp_txt, 'r') as vtxt, open(iinfo_txt, 'r') as itxt, open(indel_txt, 'w') as out:
		# placeholder until chromosome is discovered
		chrom = 0
		chrom_index = 0
		pos_index = 1

		# check to see if files are empty
		vlines = vtxt.readlines()
		ilines = itxt.readlines()

		if vlines and vlines != ['\n']:
			vtxt_empty = False
			print('vtxt is not empty')
		else:
			vtxt_empty = True
			print('vtxt is empty')
		if ilines and ilines != ['\n']:
			itxt_empty = False
			print('itxt is not empty')
		else:
			itxt_empty = True
			print('txt is empty')

		# condition gates to save time on empty files
		if vtxt_empty:
			if itxt_empty:
				# writes an empty string to the output to make sure it generates
				out.write('')
			# vtxt is empty, so the output should contain itxt
			else:
				for line in ilines:
					# since the input is formatted CHROM | POS, we extract
					split = line.split()
					if chrom == 0: # saves calculation time
						chrom = split[chrom_index]
					pos = split[pos_index]
					# write itxt line to file
					out.write(chrom + '\t' + '-i INFO/VT=SNP' + '\t' + pos + '\n')
		elif itxt_empty: # itxt is empty, so out should be identical to vtxt
			for line in vlines:
				# since the input files are formatted CHROM | POS, we extract
				split = line.split()
				if chrom == 0: # saves calculation time
					chrom = split[chrom_index]
				pos = split[pos_index]
				# write vtxt line to file
				out.write(chrom + '\t' + '-v snps' + '\t' + pos + '\n')
		else: # neither text file is empty, so we need to record the differences
			# declare the lists for comparison
			vlist = []
			ilist = []
			for line in ilines:
				ilist.append(line.split())
			for line in vlines:
				vlist.append(line.split())
			# iterate through and won't appear in the other list with the proper form
			for split in ilist:
				if split not in vlist and split:
					if chrom == 0:
						chrom = split[chrom_index]
					pos = split[pos_index]
					out.write(chrom + '\t' + '-i INFO/VT=SNP' + '\t' + pos + '\n')
			for split in vlist:
				if split not in ilist and split:
					if chrom == 0:
						chrom = split[chrom_index]
					pos = split[pos_index]
					out.write(chrom + '\t' + '-v snps' + '\t' + pos + '\n')
	return None

indel_diff(sys.argv[1], sys.argv[2], sys.argv[3])
